#!/usr/bin/env bash
set -ex

# determine code info
fossil_get_root () {
  local res
  [[ "${FOSSIL_ROOT:-}" ]] && { printf '%s\n' "${FOSSIL_ROOT}" ; return 0 ; }
  type fossil >/dev/null 2>&1 || printf '%s\n' "missing fossil command - things will probably break" 1>&2
  res="$(fossil info | awk '$1 == "local-root:" { print $2 }')"
  printf '%s\n' "${res%/}"
}
export FOSSIL_ROOT="$(fossil_get_root)"
. "$(fossil_get_root)/build-common/sh-functions"

create_gitexport

cd "${TMPDIR}/fossil-export-git"
git filter-repo --paths-from-file "${FOSSIL_ROOT}/dotfiles/historical-paths.filter" --force
git remote add gh git@s.github.com.arrjay.github.com:arrjay/dotfiles.git
git fetch --all
git push gh fossil-export
cd -
