#!/bin/sh
# a git hook to set emails in a source-dependent fashion

EMAIL=$(git config user.email)
ORIGIN=$(git config --get remote.origin.url)

TGT_EMAIL=""

if [ ! -z "${ORIGIN}" ] ; then
  case "${ORIGIN}" in
    *yojoe*|*palantir*)
      TGT_EMAIL="rbergeron@palantir.com"
      ;;
    *)
      # if we have any other origin we _probably_ want the gmail addr
      TGT_EMAIL="rbergero@gmail.com"
      ;;
  esac
fi

if [ ! -z "${TGT_EMAIL}" ] ; then
  if [ -z "${EMAIL}" ] ; then
    # no email configured - set one
    echo "Configuring committer/author email ${TGT_EMAIL}"
    git config user.email "${TGT_EMAIL}"
  else
    # see if TGT and EMAIL match
    if [ "${EMAIL}" != "${TGT_EMAIL}" ] ; then
      echo "WARN: Email address for repo and hook email address mismatch"
    fi
  fi
else
  echo "WARN: Email address not caught in pre-commit hook"
fi

# check for git-lfs and possibly update pointers
if git grep -q 'version https://.*\.github\.com/spec/v1' ; then
  echo "newly checked out repo has git lfs pointer files running git lfs hook"
  command -v git-lfs > /dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path."; exit 2; }
  git lfs post-checkout "$@"
fi
